[app]
name = "go_boilerplate"
environment = "local"
port = "5000"

  [app.auth]
  access-token-type = "paseto" #paseto or jwt
  access-token-duration = "15m"
  refresh-token-duration = "24h"
  jwt-private-key = "0z6eQbA4EZVcEbmyyojJ8FXhy0cd1jrv"
  paseto-symmetric-key = "dFRpaeCkdLuKpv65vN7QDSGm5M4H6EWe"

[cache]
  [cache.redis]
  host = "cache" # redis container name
  port = 6379
  db = 0
  pass = "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  default-expiration = "24h"
  
[db]
  [db.mysql]
  username = "root"
  password = "root"
  host = "db" # mysql container name
  port = 3306
  db-name = "boiler_db"
  max-life-in-minutes = 1
  max-idle-connections = 5
  max-open-connections = 100

[log]
debug = true
log-to-file = false
path = "go_boilerplate.log"