version: '3'

services:

  app:
    container_name: go-boilerplate-app
    build: .
    command: .docker/entrypoint.sh
    ports:
      - 5000:5000
    environment:
      WAIT_HOSTS: db:3306
      DB_MYSQL_HOST: go-boilerplate-mysql
      CACHE_REDIS_HOST: cache-redis
    volumes:
      - ./:/app   #use this volume to set the live reload
    depends_on:
      - db
      - cache
    networks:
      - app-network

  cache:
    container_name: cache-redis
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./.docker/cachedata:/data
    networks:
      - app-network
  
  db:
    container_name: go-boilerplate-mysql
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE - this is to not show the error 'mbind: Operation not permitted' in database docker log
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=boiler_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
        - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      - app-network
   
networks:
  app-network:
    driver: bridge
