name: CI test and vulnerability check
on: [push]
jobs:
  setup-mysql:
    name: Setup MySQL
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL to run the tests
        uses: mirromutth/mysql-action@v1.1
        with:
          #host port: 3800 # Optional, default value is 3306. The port of host
          #container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0.22'
          mysql database: 'boiler_db'
          mysql root password: root
          mysql user: 'root'
          mysql password: root
    
  test-application:
    name: Run test application
    needs: [setup-go, setup-mysql]
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: make test
  
  govulncheck:
    runs-on: ubuntu-latest
    needs: setup-go
    name: Run govulncheck
    steps:
      - name: Running Vulnerability Check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
