name: ci-go_boilerplate-workflow
on: [push]
jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.5

      - name: Setup MySQL to run the tests
        uses: mirromutth/mysql-action@v1.1
        with:
          #host port: 3800 # Optional, default value is 3306. The port of host
          #container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0.22'
          mysql database: 'boiler_db'
          mysql root password: root
          mysql user: 'root'
          mysql password: root
          
      - name: Run tests
        run: make test
  
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
